【发生时间】2016-2-19 
【问题描述】执行Python程序时，执行到raise e语句时卡住不返回（只发生在centos系统中）
【解决办法】重启abrt服务

【问题详情】
该Python程序yt.py内容如下：
try:
   raise  Exception( 'COUNT_ERROR' )

except Exception, e:
   raise e
该文件yt.py存放于/tmp路径下
1、切换到/tmp路径下，执行命令：python yt.py，有抛出错误，如下：
[root@centos-ci004 sequoiadb]# python /tmp/yt.py 
Traceback (most recent call last):
  File "/tmp/yt.py", line 6, in <module>
    raise e  
Exception: COUNT_ERROR
2、执行命令（使用绝对路径）：python /tmp/yt.py程序卡住，如下：
[root@centos-ci004 sequoiadb]# python /tmp/yt.py 
（卡住不返回，知道ctrl+c才返回堆栈信息）

该问题只有在centos测试机上出现，其他系统的测试机没有出现

【解决过程】
1、gdb attach pid(卡住的进程)
(gdb) info threads
* 1 Thread 0x7f8b845fc700 (LWP 29104)  0x000000396c80e890 in __connect_nocancel () from /lib64/libpthread.so.0
查看到是卡在系统调用
2、使用strace来跟踪进程执行时的系统调用
[root@centos-ci007 sequoiadb]# strace -p 29104
Process 29104 attached - interrupt to quit
connect(5, {sa_family=AF_FILE, path="/var/run/abrt/abrt.socket"}, 27
查看到卡在abrt
3、尝试重启abrt服务
service abrtd stop
service abrtd start
4、重新执行python /tmp/yt.py：不卡住，返回错误栈

【遗留问题】
使用绝对路径和相对路径的区别在哪里？